HOME    = /Users/roylee/coursera/alg-part1
JARS    = $(HOME)/algs4.jar:$(HOME)/stdlib.jar
JAVAS   = Deque.java RandomizedQueue.java


all: $(JAVAS)
	javac -cp $(JARS) $(JAVAS)

clean:
	rm -rf *.class
